{
  "package_name": "django-allauth",
  "patch_versions": [
    "65.2.0"
  ],
  "vulnerable_ranges": [
    [
      "0.63.0",
      "65.1.0"
    ]
  ],
  "cwe": [
    "CWE-307"
  ],
  "tldr": "Affected versions of this package are vulnerable to a bruteforce attack due to the lack of enforcement of the 'settings.ACCOUNT_EMAIL_VERIFICATION_BY_CODE_MAX_ATTEMPTS' parameter. This issue arises because the number of attempts allowed for email account verification is not properly limited, allowing attackers to try many verification codes in a short amount of time.",
  "doest_this_affect_me": "You are affected if you are using a version that falls within the vulnerable range.",
  "how_to_fix": "Upgrade the `django-allauth` library to the patch version.",
  "reporter": "",
  "vulnerable_to": "Improper Restriction of Excessive Authentication Attempts",
  "related_cve_id": "",
  "language": "python",
  "severity_class": "MEDIUM",
  "aikido_score": 42,
  "changelog": "https://github.com/pennersr/django-allauth/blob/main/ChangeLog.rst",
  "published": "2024-11-08",
  "last_modified": "2024-11-08"
}