{
  "id" : "AIKIDO-2024-10439",
  "package_name" : "viztracer",
  "patch_versions" : [ "0.17.1" ],
  "vulnerable_ranges" : [ [ "0.0.3", "0.17.0" ] ],
  "cwe" : [ "CWE-400" ],
  "tldr" : "Affected versions of this package are vulnerable to Denial of Service (DoS) attacks due to unexpected segmentation faults in the trace functionality. This can lead to application crashes and service unavailability when certain conditions trigger these faults.",
  "doest_this_affect_me" : "You are affected if you are using a version that falls within the vulnerable range.",
  "how_to_fix" : "Upgrade the `viztracer` library to the patch version.",
  "reporter" : "",
  "vulnerable_to" : "Denial of Service (DoS)",
  "related_cve_id" : "",
  "language" : "python",
  "severity_class" : "LOW",
  "aikido_score" : 28,
  "changelog" : "https://github.com/gaogaotiantian/viztracer/releases/tag/0.17.1",
  "package_name_alias" : null,
  "package_wildcard_ends_in" : null,
  "package_wildcard_contains" : null,
  "extra_specific_non_vulnerable_versions" : null,
  "unaffected_distros" : null,
  "simplify_version_if_has_patch_part" : false,
  "published" : "2024-11-13",
  "last_modified" : "2024-11-13"
}